### ISSUE TITLE
Parts of library are private/internal

### ISSUE THREAD

**Issue by rojiani** [saurabharora90/CustomTabs-Kotlin#1]
I'm interested in using this library, but some of the classes & methods used in the README example are marked `private`, which prevents them from being called from another module. Specifically:

* The `launchWithFallback` in CustomTabsIntentExtensions.kt isn't visible (I'm not entirely sure why since it isn't `internal` or `private`, but in the library jar, the `extensions` package is missing).
* in `CustomTabActivityHelper`: `bindCustomTabsService` & `unbindCustomTabsService` are `private`. This wasn't in the README example, but looking at Google's [custom-tabs-client](https://github.com/GoogleChrome/custom-tabs-client/blob/bd0bd8af3755f0941c766403c4603a1d8d2ef0f4/demos/src/main/java/org/chromium/customtabsdemos/ServiceConnectionActivity.java#L68-L74) samples, it looks like these should may need to be called in the Activity).

**Comment by saurabharora90** [comment]
- For the `launchWithFallback`, did you have a look at the sample? That seems to be working. Could share a small demo of what you are trying to do? https://github.com/saurabharora90/CustomTabs-Kotlin/tree/master/app/src/main/java/com/saurabharora/customtabs/sample

- The `bindCustomTabsService` and `unbindCustomTabsService` were made private on purpose since I use a Lifecycle object to observe and call these methods, without any involvement of the consumer. Hence, a consumer should no longer need access to these methods.

**Comment by rojiani** [comment]
Here's a demo - 
[custom-tabs-kotlin-demo.zip](https://github.com/saurabharora90/CustomTabs-Kotlin/files/3009134/custom-tabs-kotlin-demo.zip)

The demo is pretty similar to the sample. After exploring the sample, it looks like the only issue is that launchWithFallback isn't visible (CustomTabsIntentExtensions.kt). So in the demo, i've copied in CustomTabsIntentExtensions.kt (& CustomTabsHelper, since this is a dependency of launchWithFallback), so that it compiles.

In your sample, launchWithFallback is visible. You are declaring a dependency on the `customtabs`  project ([app/build.gradle](https://github.com/saurabharora90/CustomTabs-Kotlin/blob/master/app/build.gradle#L27)). If you make the following change, launchWithFallback will no longer be visible:

```
dependencies {
    // ...
   implementation project(':customtabs')
}
```

```
dependencies {
    // ...
    implementation 'com.saurabharora.customtabs:customtabs:1.0.0'
    // may also then need to add this:
    // api 'androidx.browser:browser:1.0.0-rc01'
}
```
I'm not sure why exactly CustomTabsIntentExtensions.kt isn't being compiled into the library's jar, though...

**Comment by saurabharora90** [comment]
Seems like the readme isn't up to date. My mistake.

Use version 1.1 instead of 1.0.0

**Comment by rojiani** [comment]
That resolved it. Thanks!
